### ISSUE TITLE
Wrong item position used when data set changes during swipe

### ISSUE THREAD

**Issue by hroberts693** [h6ah4i/android-advancedrecyclerview#133]
The original position of a swiped item is saved by RecyclerViewSwipeManager in startSwiping and used without further validation in finishSwiping and SwipingItemOperator's update method.  Data set changes between startSwiping and finishSwiping invalidate this position - this leads to problems when the swipe action is used to remove items in onSlideAnimationEnd or similar.

A proposed patch to fix this bug is available at http://pastebin.com/DzQZiKQD

**Comment by h6ah4i** [comment]
Thank for your issue report and the bug fix patch! I have just merged it into the develop branch ;)

**Comment by hroberts693** [comment]
SwipeableItemWrapperAdapter was also saving the original item position - as a result the wrong flags were set in onBindViewHolder.  This was replaced with the swiped item's ID in the following patch (against commit 8f7af317cc93f566336f785341b93b2ec7f663b9): http://pastebin.com/FLUeLKa2

**Comment by h6ah4i** [comment]
I've just released v0.8.3 and it includes your patches. Thank you!

**Comment by pixelbendr** [comment]
The app still crashes using the latest version of the support library. Does this update fix all those issues.

**Comment by h6ah4i** [comment]
@pixelbendr Hi. Do you mean the exact same issue is still present? If so I will re-open this issue and continue disscussing about it, if not you should create a new issue report. 

The issue #120 and #122 are still marked as open and I have not figured out whether they are just "questions" or "BUGs". I need more info to investigate them. Could you provide full of the stack trace dump or a sample project which can reproduce the issue?

**Comment by pixelbendr** [comment]
This is the stack trace

```
Fatal Exception: java.lang.AbstractMethodError: abstract method not implemented
       at android.support.v7.widget.RecyclerView$ItemAnimator.animateAppearance(RecyclerView.java)
       at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java)
       at android.support.v7.widget.RecyclerView.access$800(RecyclerView.java)
       at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java)
       at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at com.flipboard.bottomsheet.BottomSheetLayout.onLayout(BottomSheetLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
       at android.widget.LinearLayout.onLayout(LinearLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
       at android.widget.LinearLayout.onLayout(LinearLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
       at android.view.Choreographer.doCallbacks(Choreographer.java)
       at android.view.Choreographer.doFrame(Choreographer.java)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
       at android.os.Handler.handleCallback(Handler.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by h6ah4i** [comment]
@pixelbendr That is a completely different issue. Please create a new issue and give me these additional info;

- output message of `./gradlew :app:dependencies`
- Android OS version

**Comment by pixelbendr** [comment]
@h6ah4i I have reverted to the last working version. So I will create a new issue when I decide to upgrade. Thanks for this.

**Comment by h6ah4i** [comment]
I think that was a version mismatching of the  support-v7-recyclerview library. The v23.1.0 has introduced a breaking change of RecyclerView.ItemAnimator. Maybe you were using the latest ARV library with old incompatible support-v7-recyclerview.
